name: Pre-release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm run build

      - name: Set version variable
        id: set-version
        run: echo "version=$(node -p 'require("./package.json").version')" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: JarvisGPT_Chrome_Extension_v${{ steps.set-version.outputs.version }}
          path: build/*
