name: Pre-release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - uses: actions/upload-artifact@v3
        with:
          name: JarvisGPT_Chrome_Extension_v${{ steps.package-version.outputs.current-version }}
          path: build/chromium/*
